###
POST http://localhost:8080/appointment/bulkSave
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="appointments.csv"
Content-Type: text/csv

< ./appointments.csv
--WebAppBoundary--