###
POST http://localhost:8080/client/save
Content-Type: application/json

{
  "identifier": "test_identifier",
  "firstName": "grzegorz",
  "lastName": "brzeczyszczykiewicz",
  "email": "grzegorz.brzeczyszczykiewicz@mail.com",
  "phone": "123456789",
  "gender": "MALE",
  "banned": false
}

###
POST http://localhost:8080/client/bulkSave
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="clients.csv"
Content-Type: text/csv

< ./clients.csv
--WebAppBoundary--

###
GET http://localhost:8080/client/fetch/test_identifier

###
GET http://localhost:8080/client/fetchTopClients?amount=50&since=2018-01-01

###
PATCH http://localhost:8080/client/update
Content-Type: application/json

{
  "identifier": "test_identifier",
  "firstName": "grzegorz",
  "email": "grzegorz.brzeczyszczykiewicz2@mail.com",
  "phone": "987654321"
}

###
DELETE http://localhost:8080/client/delete/test_identifier